package com.example.dczs.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dczs.entity.AddModifyMenuBean;
import com.example.dczs.entity.OrderFormBean;
import com.example.dczs.entity.ShoppingCartBean;
import com.example.dczs.entity.UserInfoBean;

import com.example.dczs.greendao.AddModifyMenuBeanDao;
import com.example.dczs.greendao.OrderFormBeanDao;
import com.example.dczs.greendao.ShoppingCartBeanDao;
import com.example.dczs.greendao.UserInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addModifyMenuBeanDaoConfig;
    private final DaoConfig orderFormBeanDaoConfig;
    private final DaoConfig shoppingCartBeanDaoConfig;
    private final DaoConfig userInfoBeanDaoConfig;

    private final AddModifyMenuBeanDao addModifyMenuBeanDao;
    private final OrderFormBeanDao orderFormBeanDao;
    private final ShoppingCartBeanDao shoppingCartBeanDao;
    private final UserInfoBeanDao userInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addModifyMenuBeanDaoConfig = daoConfigMap.get(AddModifyMenuBeanDao.class).clone();
        addModifyMenuBeanDaoConfig.initIdentityScope(type);

        orderFormBeanDaoConfig = daoConfigMap.get(OrderFormBeanDao.class).clone();
        orderFormBeanDaoConfig.initIdentityScope(type);

        shoppingCartBeanDaoConfig = daoConfigMap.get(ShoppingCartBeanDao.class).clone();
        shoppingCartBeanDaoConfig.initIdentityScope(type);

        userInfoBeanDaoConfig = daoConfigMap.get(UserInfoBeanDao.class).clone();
        userInfoBeanDaoConfig.initIdentityScope(type);

        addModifyMenuBeanDao = new AddModifyMenuBeanDao(addModifyMenuBeanDaoConfig, this);
        orderFormBeanDao = new OrderFormBeanDao(orderFormBeanDaoConfig, this);
        shoppingCartBeanDao = new ShoppingCartBeanDao(shoppingCartBeanDaoConfig, this);
        userInfoBeanDao = new UserInfoBeanDao(userInfoBeanDaoConfig, this);

        registerDao(AddModifyMenuBean.class, addModifyMenuBeanDao);
        registerDao(OrderFormBean.class, orderFormBeanDao);
        registerDao(ShoppingCartBean.class, shoppingCartBeanDao);
        registerDao(UserInfoBean.class, userInfoBeanDao);
    }
    
    public void clear() {
        addModifyMenuBeanDaoConfig.clearIdentityScope();
        orderFormBeanDaoConfig.clearIdentityScope();
        shoppingCartBeanDaoConfig.clearIdentityScope();
        userInfoBeanDaoConfig.clearIdentityScope();
    }

    public AddModifyMenuBeanDao getAddModifyMenuBeanDao() {
        return addModifyMenuBeanDao;
    }

    public OrderFormBeanDao getOrderFormBeanDao() {
        return orderFormBeanDao;
    }

    public ShoppingCartBeanDao getShoppingCartBeanDao() {
        return shoppingCartBeanDao;
    }

    public UserInfoBeanDao getUserInfoBeanDao() {
        return userInfoBeanDao;
    }

}
